use_frameworks!

target 'SBNPopoverController_Example' do
  pod 'SBNPopoverController', :path => '../'

  target 'SBNPopoverController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
